name: Halo
options:
  bundleIdPrefix: com.karanuppal
  deploymentTarget:
    iOS: "17.0"

targets:
  HaloApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: Halo
        SWIFT_MODULE_NAME: HaloApp
        PRODUCT_BUNDLE_IDENTIFIER: com.karanuppal.HaloApp
    sources:
      - path: HaloApp/Sources
      - path: Shared
    resources:
      - path: HaloApp/Resources
    info:
      path: HaloApp/Resources/Info.plist
    dependencies:
      - target: HaloMessagesExtension
        embed: true

  HaloMessagesExtension:
    type: app-extension
    platform: iOS
    productType: com.apple.product-type.app-extension.messages
    settings:
      base:
        PRODUCT_NAME: HaloMessagesExtension
        SWIFT_MODULE_NAME: HaloMessagesExtension
        PRODUCT_BUNDLE_IDENTIFIER: com.karanuppal.HaloApp.HaloMessagesExtension
    sources:
      - path: HaloMessagesExtension/Sources
      - path: Shared
    resources:
      - path: HaloMessagesExtension/Resources
    info:
      path: HaloMessagesExtension/Resources/Info.plist
      properties:
        CFBundleDisplayName: Halo
        NSExtension:
          NSExtensionPointIdentifier: com.apple.message-payload-provider
          NSExtensionPrincipalClass: $(PRODUCT_MODULE_NAME).MessagesViewController
          NSExtensionAttributes:
            MSMessagesAppPresentationStyle: compact

  HaloAppUITests:
    type: bundle.ui-testing
    platform: iOS
    settings:
      base:
        PRODUCT_NAME: HaloAppUITests
        SWIFT_MODULE_NAME: HaloAppUITests
        PRODUCT_BUNDLE_IDENTIFIER: com.karanuppal.HaloAppUITests
        GENERATE_INFOPLIST_FILE: "YES"
    sources:
      - path: HaloAppUITests
    dependencies:
      - target: HaloApp
